/*

Author: Anna Neander (2021)
Based on example from https://github.com/is1200-example-projects/hello-temperature
written by Axel Isaksson.

For copyright and licensing, see file COPYING
*/




#include <stdint.h>   /* Declarations of uint_32 and the like */
#include <pic32mx.h>  /* Declarations of system-specific addresses etc */

#include "rgb_i2c.h"




/*
  power on and init. send
*/
void rgb_init(void){


  /* Set up i2c. from temp sensor example */
  void i2c_setup() {
    /* Set up i2c */
  	I2C1CON = 0x0;
  	/* I2C Baud rate should be less than 400 kHz, is generated by dividing
  	the 40 MHz peripheral bus clock down */
  	I2C1BRG = 0x0C2;
  	I2C1STAT = 0x0;
  	I2C1CONSET = 1 << 13; //SIDL = 1
  	I2C1CONSET = 1 << 15; // ON = 1    /*power on?*/

  }








}
